server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cw2m6xryal2i.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220929-junil?allowMultiQueries=true
    username: junil
    password: 1q2w3e4r

  security:
    user:
      name: admin
      password: 1q2w3e4r
    oauth2:
      client:
        registration:
          google:
            clientId: 463278431196-as9773icaq0pp59mibg3ap62v1un4n7b.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile


mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:/junil/junil/web/springboot/stussy-clone-20220929-junil/upload/